Fix the URL to point to the proper location
Uninett/python-logging-humio pull request #5
Opened 2021-06-04 10:05 UTC by limedaniel

When I clicked on the `Homepage` link on PyPI and got a 404, I thought that the project might be abandonware.  After some digging though, I found this, so I thought I'd correct the `url` value in `setup.py`.

2023-05-30 15:01 UTC, richtier-shell commented
also needs changing here: https://github.com/Uninett/python-logging-humio/blob/60778b78824b3804f81052ee5413a2a7ea992d2f/pyproject.toml#L32

2023-05-30 15:02 UTC, richtier-shell requested changes
also needs changing here: https://github.com/Uninett/python-logging-humio/blob/60778b78824b3804f81052ee5413a2a7ea992d2f/pyproject.toml#L32

2023-08-11 06:02 UTC, hmpf approved these changes

2023-08-11 06:38 UTC, hmpf commented
Yo, maybe in use by others than ourselves!

The url will be fixed in the next release, 1.0.5.

2023-08-11 07:11 UTC, closed without merging